/*
This file is part of sasJSON.

sasJSON is free software: you can redistribute it and/or modify
it under the terms of the Lesser GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

sasJSON is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with sasJSON.  If not, see <http://www.gnu.org/licenses/>
*/

#ifndef sasJSON__errorcodes_h
#define sasJSON__errorcodes_h

#include <sasCore/errorcodes.h>

#define _SAS_JSON__ERROR_BASE_ 5100

#define SAS_JSON__ERROR__CONFIG_READER__CANNOT_GET_ENTRY SAS_CORE__ERROR__CONFIG_READER__CANNOT_GET_ENTRY
#define SAS_JSON__ERROR__CONFIG_READER__ENTRY_NOT_FOUND SAS_CORE__ERROR__CONFIG_READER__ENTRY_NOT_FOUND
#define SAS_JSON__ERROR__CONFIG_READER__UNEXPECTED_ERROR SAS_CORE__ERROR__CONFIG_READER__UNEXPECTED_ERROR
#define SAS_JSON__ERROR__CONFIG_READER__INVALID_ARGUMENT SAS_CORE__ERROR__CONFIG_READER__INVALID_ARGUMENT
#define SAS_JSON__ERROR__CONFIG_READER__CANNOT_READ_CONFIG SAS_CORE__ERROR__CONFIG_READER__CANNOT_READ_CONFIG
#define SAS_JSON__ERROR__CONFIG_READER__INVALID_LIST_VALUE SAS_CORE__ERROR__CONFIG_READER__INVALID_LIST_VALUE
#define SAS_JSON__ERROR__CONFIG_READER__TYPE_MISMATCH SAS_CORE__ERROR__CONFIG_READER__TYPE_MISMATCH
#define SAS_JSON__ERROR__INVOKER__INVALID_DATA SAS_CORE__ERROR__INVOKER__INVALID_DATA
#define SAS_JSON__ERROR__INVOKER__UNSUPOPORTED_DATA SAS_CORE__ERROR__INVOKER__UNSUPPORTED_DATA
#define SAS_JSON__ERROR__INVOKER__TYPE_MISMATCH SAS_CORE__ERROR__INVOKER__TYPE_MISMATCH
#define SAS_JSON__ERROR__INVOKER__UNSUPPORTED_FUNCTIONALITY SAS_CORE__ERROR__INVOKER__UNSUPPORTED_FUNCTIONALITY
//#define SAS_JSON__ERROR__ SAS_CORE__ERROR__
//#define SAS_JSON__ERROR__ SAS_CORE__ERROR__
//#define SAS_JSON__ERROR__ SAS_CORE__ERROR__
//#define SAS_JSON__ERROR__ SAS_CORE__ERROR__
//#define SAS_JSON__ERROR__ SAS_CORE__ERROR__


#define SAS_JSON__ERROR__STREAM_READER__CANNOT_OPEN_FILE _SAS_JSON__ERROR_BASE_+1
#define SAS_JSON__ERROR__STREAM_READER__PARSE_ERROR _SAS_JSON__ERROR_BASE_+2
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+3
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+4
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+5
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+6
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+7
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+8
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+9
//#define SAS_JSON__ERROR__ _SAS_JSON__ERROR_BASE_+10


#endif //sasJSON__errorcodes_h
