/*
This file is part of sasCore.

sasCore is free software: you can redistribute it and/or modify
it under the terms of the Lesser GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

sasCore is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with sasCore.  If not, see <http://www.gnu.org/licenses/>
*/

#ifndef sasCore__errorcodes_h
#define sasCore__errorcodes_h

#define _SAS_CORE__ERROR_BASE_ 100

#define SAS_CORE__ERROR__APPLICATION__NO_COMPONENTS _SAS_CORE__ERROR_BASE_+1
#define SAS_CORE__ERROR__COMPONENT_LOADER__NO_ENTRANCE  _SAS_CORE__ERROR_BASE_+2
#define SAS_CORE__ERROR__INTERFACE_MANAGER__ALREADY_REGISTERED _SAS_CORE__ERROR_BASE_+3
#define SAS_CORE__ERROR__LIBRARY_LOADER__CANNOT_OPEN _SAS_CORE__ERROR_BASE_+4
#define SAS_CORE__ERROR__LIBRARY_LOADER__MISSING_PROCEDURE _SAS_CORE__ERROR_BASE_+5
#define SAS_CORE__ERROR__OBJECT_REGISTRY__ALREADY_REGISTERED _SAS_CORE__ERROR_BASE_+6
#define SAS_CORE__ERROR__OBJECT_REGISTRY__TYPE_NOT_FOUND _SAS_CORE__ERROR_BASE_+7
#define SAS_CORE__ERROR__OBJECT_REGISTRY__OBJECT_NOT_FOUND _SAS_CORE__ERROR_BASE_+8
#define SAS_CORE__ERROR__CONFIG_READER__CANNOT_GET_ENTRY  _SAS_CORE__ERROR_BASE_+9
#define SAS_CORE__ERROR__CONFIG_READER__ENTRY_NOT_FOUND  _SAS_CORE__ERROR_BASE_+10
#define SAS_CORE__ERROR__CONFIG_READER__UNEXPECTED_ERROR  _SAS_CORE__ERROR_BASE_+11
#define SAS_CORE__ERROR__CONFIG_READER__INVALID_ARGUMENT  _SAS_CORE__ERROR_BASE_+12
#define SAS_CORE__ERROR__CONFIG_READER__CANNOT_READ_CONFIG  _SAS_CORE__ERROR_BASE_+13
#define SAS_CORE__ERROR__CONFIG_READER__INVALID_LIST_VALUE  _SAS_CORE__ERROR_BASE_+14
#define SAS_CORE__ERROR__CONFIG_READER__TYPE_MISMATCH  _SAS_CORE__ERROR_BASE_+15
#define SAS_CORE__ERROR__INTERNAL_ERROR  _SAS_CORE__ERROR_BASE_+16
#define SAS_CORE__ERROR__INVOKER__INVALID_DATA  _SAS_CORE__ERROR_BASE_+17
#define SAS_CORE__ERROR__INVOKER__UNSUPPORTED_DATA  _SAS_CORE__ERROR_BASE_+18
#define SAS_CORE__ERROR__INVOKER__TYPE_MISMATCH  _SAS_CORE__ERROR_BASE_+19
#define SAS_CORE__ERROR__INVOKER__UNSUPPORTED_FUNCTIONALITY  _SAS_CORE__ERROR_BASE_+20
#define SAS_CORE__ERROR__COMPONENT__INIT_FAILURE  _SAS_CORE__ERROR_BASE_+21
#define SAS_CORE__ERROR__CONNECTOR__CANNOT_CONNECT  _SAS_CORE__ERROR_BASE_+22
#define SAS_CORE__ERROR__CONNECTOR__CONNECTION_REFUSED  _SAS_CORE__ERROR_BASE_+23
#define SAS_CORE__ERROR__CONNECTOR__MISSING_CONNECTION_DATA  _SAS_CORE__ERROR_BASE_+24
#define SAS_CORE__ERROR__CONNECTOR__UNEXPECTED_ERROR  _SAS_CORE__ERROR_BASE_+25
#define SAS_CORE__ERROR__CONNECTOR__INVALID_CONNECTION_DATA  _SAS_CORE__ERROR_BASE_+26
#define SAS_CORE__ERROR__CONNECTOR__SERVER__NOT_IMPLEMENTED  _SAS_CORE__ERROR_BASE_+27
#define SAS_CORE__ERROR__CONNECTOR__SERVER__ERROR  _SAS_CORE__ERROR_BASE_+28
#define SAS_CORE__ERROR__CONNECTOR__SERVER__FATAL_ERROR _SAS_CORE__ERROR_BASE_+29
#define SAS_CORE__ERROR__CONNECTOR__COMMUNICATION_FAILURE  _SAS_CORE__ERROR_BASE_+30
#define SAS_CORE__ERROR__CONNECTOR__SERVER_NOT_FOUND  _SAS_CORE__ERROR_BASE_+31
#define SAS_CORE__ERROR__INTERFACE__CANNOT_REGISTER_SERVER  _SAS_CORE__ERROR_BASE_+32
#define SAS_CORE__ERROR__INTERFACE__COMMUNICATION_FAILURE _SAS_CORE__ERROR_BASE_+33
#define SAS_CORE__ERROR__INTERFACE__UNEXPECTED_ERROR _SAS_CORE__ERROR_BASE_+34
#define SAS_CORE__ERROR__MODULE__INIT_FAILURE  _SAS_CORE__ERROR_BASE_+35
#define SAS_CORE__ERROR__MODULE__MISSING_CONFIG_ENTRY  _SAS_CORE__ERROR_BASE_+35
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+36
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+37
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+38
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+39
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+40
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+41
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+42
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+43
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+44
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+45
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+46
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+47
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+48
//#define SAS_CORE__ERROR__  _SAS_CORE__ERROR_BASE_+49

#endif // sasCore__errorcodes_h
